eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:18761/eureka/

spring:
  application:
    name: tks-zuul
  http:
    multipart:
      max-file-size: 2000Mb
      max-request-size: 2000Mb
  zipkin:
    base-url: http://localhost:19411
  sleuth:
    sampler:
      percentage: 1.0
      
#feign:
#  hystrix:
#    enabled: true
ribbon:
  ReadTimeout: 180000
  ConnectTimeout: 180000
  OkToRetryOnAllOperations: true
  MaxAutoRetriesNextServer: 2
  MaxAutoRetries: 0
hystrix:
    command:
        default:
            execution:
                timeout:
                    enabled: false
                isolation:
                    thread:
                        timeout-in-milliseconds: 3000000
                        interruptOnTimeout: false
    metrics:
      enabled: true
      polling-interval-ms: 200000

zuul:
  retryable: false
  host:
    connect-timeout-millis: 30000
    socket-timeout-millis: 30000
  routes:
    tks-web:
      path: /tks-web/**
      serviceId: tks-web

server:
  port: 17777